### ISSUE TITLE
How to build with unstable pre-releases of Go

### ISSUE THREAD

**Issue by skaldarnar** [cli/gh-extension-precompile#11]
I'm trying to build a little extension and (for whatever esoteric reason) would like to build with the [1.18beta1](https://go.dev/dl/#go1.18beta1) version of Go. Is there a way to do that?

I found a paragraph in the [docs of actions/setup-go](https://github.com/actions/setup-go#V2) that looks like it should in theory be possible to specify non-release versions:

```
  - uses: actions/setup-go@v2
    with:
      stable: 'false'
      go-version: '1.14.0-rc1' # The Go version to download (if necessary) and use.
```

However, the corresponding part in this action only allows to set the `go-version`, but we cannot set the `stable` flag to false, can we?

https://github.com/cli/gh-extension-precompile/blob/b3199c540c5b863b00e24c36783ffdafa9bbc96b/action.yml#L20-L22

Would a fix be as simple as adding another input option and passing that through?
