### ISSUE TITLE
Make go version a variable

### ISSUE THREAD

**Issue by heaths** [cli/gh-extension-precompile#5]
https://github.com/cli/gh-extension-precompile/blob/7d68a916d25a2c6fb201a9c9f49adb3c07b8c214/action.yml#L19

Rather than hardcoding if we require newer compiler features, could this be made a variable with a default e.g.,

```yaml
inputs: 
  go-version:
    description: 'The Go version to download (if necessary) and use. Supports semver spec and ranges.'
    default: '1.16'

# ...

    - uses: actions/setup-go@v2
      with:
        go-version: ${{ inputs.go-version }}
```
